
using Khorshid.Data;
using Khorshid.Models;
using Khorshid.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Media;

namespace Khorshid.DataAccessLayer
{
    public static class KhorshidDataManager
    {

        public static List<TownData> GetModifiedTownData()
        {
            var context = new KhorshidContext();
            return context.TownData.ToArray().Select(town => new TownData()
            {
                Id = town.Id,
                Town = town.Town,
                Price = town.Price + " تومان",
                Tag = town.Tag
            }).ToList();
        }

        public static void InitilizeDefaultValues()
        {
            var context = new KhorshidContext();

            if(context.TownData.ToList().Count == 0)
            {
                AddDefaultTownData(context);
            }

            if(context.Drivers.ToList().Count == 0)
            {
                AddDefaultDriver(context);
            }

        }

        private static void AddDefaultTownData(KhorshidContext context)
        {
            var data = new List<TownData>
            {
                new TownData(){ Town = "آبکنار انزلی", Price = "50000" , Tag = "آب کنار اب آب کنار انزلی"},
                new TownData(){ Town = "آزاد محله کشل", Price = "7500", Tag = "ازاد" },
                new TownData(){ Town = "آستارا", Price = "140000", Tag = "" },
                new TownData(){ Town = "آمل", Price = "190000", Tag = "امل" },
                new TownData(){ Town = "ابرهیم سرا", Price = "8000", Tag = "" },
                new TownData(){ Town = "اردبیل", Price = "207000", Tag = "" },
                new TownData(){ Town = "اسالم", Price = "75000", Tag = "" },
                new TownData(){ Town = "اسپیلی", Price = "92000", Tag = "" },
                new TownData(){ Town = "استخر بیجار (جاده کیاشهر)", Price = "6000", Tag = "" },
                new TownData(){ Town = "استخر بیجار (جاده رودبنه)", Price = "6000", Tag = "" },
                new TownData(){ Town = "اشلیکی اول", Price = "8500", Tag = "ایشیلکی اشلیکی" },
                new TownData(){ Town = "اشلیکی آخر", Price = "10500", Tag = "ایشیلکی اشلیکی اخر " },
                new TownData(){ Town = "اشمان دهکا", Price = "11000", Tag = "" },
                new TownData(){ Town = "اشمان کماچال", Price = "9000", Tag = "" },
                new TownData(){ Town = "اصفهان", Price = "520000", Tag = "" },
                new TownData(){ Town = "اطاق ور لنگرود", Price = "35000", Tag = "اتاق" },
                new TownData(){ Town = "اکبر آباد", Price = "18000", Tag = "اباد" },
                new TownData(){ Town = "امام زاده هاشم", Price = "52000", Tag = "" },
                new TownData(){ Town = "امام زاده ابراهیم", Price = "90000", Tag = "" },
                new TownData(){ Town = "امام زاده عبدالله", Price = "230000", Tag = "" },
                new TownData(){ Town = "امشل", Price = "5500", Tag = "" },
                new TownData(){ Town = "املش", Price = "35000", Tag = "" },
                new TownData(){ Town = "امیر سلطان امیر هنده", Price = "8000", Tag = "" },
                new TownData(){ Town = "امیر کیاسر کیاشهر", Price = "16000", Tag = "" },
                new TownData(){ Town = "امیر هنده دهشال", Price = "15000", Tag = "" },
                new TownData(){ Town = "امین اباد خشک بیجار", Price = "29000", Tag = "آباد" },
                new TownData(){ Town = "انارستان سیاهکل", Price = "14000", Tag = "" },
                new TownData(){ Town = "انبارسر", Price = "19500", Tag = "انبار" },
                new TownData(){ Town = "انزلی", Price = "50000", Tag = "" },
                new TownData(){ Town = "ایشکا بازکیا گوراب", Price = "10500", Tag = "" },
                new TownData(){ Town = "ایوان استخر", Price = "25000", Tag = "" },
                new TownData(){ Town = "ایشکا رودبنه", Price = "18000", Tag = "" },
                new TownData(){ Town = "اسلام ده کتشست آبادان", Price = "17000", Tag = "ابادان" },
                new TownData(){ Town = "ایزبرم زندان", Price = "20000", Tag = "" },
                new TownData(){ Town = "آقا سید ابراهیم شیشه گوراب", Price = "25000", Tag = "اقا" },
                new TownData(){ Town = "بابل", Price = "207000", Tag = "" },
                new TownData(){ Town = "بابلسر", Price = "195000", Tag = "" },
                new TownData(){ Town = "بازان", Price = "8500", Tag = "" },
                new TownData(){ Town = "بازکیاگوراب", Price = "8000", Tag = "" },
                new TownData(){ Town = "بالا رود پشت", Price = "29000", Tag = "" },
                new TownData(){ Town = "بارکوسرا", Price = "18000", Tag = "" },
                new TownData(){ Town = "بلسه بنه", Price = "20000", Tag = "" },
                new TownData(){ Town = "بیدرون سیاهکل", Price = "18000", Tag = "" },
                new TownData(){ Town = "بیربنه", Price = "10500", Tag = "" },
                new TownData(){ Town = "بین کلایه", Price = "15000", Tag = "" },
                new TownData(){ Town = "بالالات", Price = "4600", Tag = "" },
                new TownData(){ Town = "بلکده لاشه", Price = "14000", Tag = "" },
                new TownData(){ Town = "بیجاربنه بازار ده", Price = "17000", Tag = "" },
                new TownData(){ Town = "یازارده لفمجان", Price = "16000", Tag = "" },
                new TownData(){ Town = "ابیاری اول", Price = "4000", Tag = "آبیاری" },
                new TownData(){ Town = "اراک", Price = "370000", Tag = "" },
                new TownData(){ Town = "ایستگاه دمچال سیاهکل", Price = "21000", Tag = "" },
                new TownData(){ Town = "پایین رود پشت", Price = "29000", Tag = "" },
                new TownData(){ Town = "پاسگاه فرهاد (از کیاشهر)", Price = "17000", Tag = "" },
                new TownData(){ Town = "پاشاکی", Price = "27500", Tag = "" },
                new TownData(){ Town = "پرکاپشت مهدی خانی", Price = "6500", Tag = "" },
                new TownData(){ Town = "پرکاپشت یاور زاده", Price = "7000", Tag = "" },
                new TownData(){ Town = "پسی خان رشت", Price = "35000", Tag = "" },
                new TownData(){ Town = "پشل", Price = "9000", Tag = "پوشل" },
                new TownData(){ Town = "پهمدان", Price = "14000", Tag = "" },
                new TownData(){ Town = "پینچاه اول", Price = "5500", Tag = "" },
                new TownData(){ Town = "پینچاه اخر", Price = "7000", Tag = "آخر" },
                new TownData(){ Town = "پل زمانی رودبنه", Price = "12500", Tag = "" },
                new TownData(){ Town = "پر شکوه", Price = "26500", Tag = "" },
                new TownData(){ Town = "پهمدان لشت نشا", Price = "22000", Tag = "" },
                new TownData(){ Town = "پرکاپشت مهدی خانی پایین", Price = "7000", Tag = "" },
                new TownData(){ Town = "تازه اباد", Price = "7000", Tag = "تازاباد تازه آباد" },
                new TownData(){ Town = "تاسنده", Price = "17000", Tag = "" },
                new TownData(){ Town = "تاکستان", Price = "16000", Tag = "" },
                new TownData(){ Town = "تبریز", Price = "340000", Tag = "" },
                new TownData(){ Town = "تجن", Price = "7000", Tag = "" },
                new TownData(){ Town = "تجن گوکه", Price = "8000", Tag = "" },
                new TownData(){ Town = "ترمینال رشت", Price = "29000", Tag = "" },
                new TownData(){ Town = "ترمینال لاهیجان", Price = "11000", Tag = "" },
                new TownData(){ Town = "تمچال", Price = "6500", Tag = "" },
                new TownData(){ Town = "تنکابن", Price = "80000", Tag = "شهسوار" },
                new TownData(){ Town = "تهام امیر سلطان", Price = "9000", Tag = "" },
                new TownData(){ Town = "تهران ازادی", Price = "230000", Tag = "" },
                new TownData(){ Town = "توستان", Price = "10000", Tag = "" },
                new TownData(){ Town = "تازه اباد چاف", Price = "38000", Tag = "" },
                new TownData(){ Town = "تمشل لاهیجان", Price = "18500", Tag = "" },
                new TownData(){ Town = "تالش محله لنگرود", Price = "17000", Tag = "" },
                new TownData(){ Town = "تهران فرودگاه امام", Price = "260000", Tag = "" },
                new TownData(){ Town = "جفرود", Price = "23000", Tag = "" },
                new TownData(){ Town = "جمعه بازار", Price = "44000", Tag = "" },
                new TownData(){ Town = "جو پشت طارمسر", Price = "", Tag = " تارم طارم تارمسر جوپشت" },
                new TownData(){ Town = "جو پشت کشل", Price = "7000", Tag = "جوپشت" },
                new TownData(){ Town = "جوریاب لشت نشا", Price = "18500", Tag = "" },
                new TownData(){ Town = "جیرنده لشت نشا", Price = "14000", Tag = "" },
                new TownData(){ Town = "جیرسو ششکل", Price = "15000", Tag = "شیشکل" },
                new TownData(){ Town = "جیرباغ دستک", Price = "37500", Tag = "" },
                new TownData(){ Town = "چابکسر", Price = "57000", Tag = "" },
                new TownData(){ Town = "چاف", Price = "31000", Tag = "" },
                new TownData(){ Town = "چالوس", Price = "100000", Tag = "" },
                new TownData(){ Town = "چمخاله", Price = "30000", Tag = "" },
                new TownData(){ Town = "چورکوچان", Price = "5500", Tag = "" },
                new TownData(){ Town = "چولاب", Price = "10000", Tag = "" },
                new TownData(){ Town = "چارده شیرکوه بالا", Price = "12000", Tag = "" },
                new TownData(){ Town = "چارده شیرکوه پایین", Price = "13000", Tag = "" },
                new TownData(){ Town = "چارده کاچا", Price = "13000", Tag = "" },
                new TownData(){ Town = "چوکا اسالم", Price = "80000", Tag = "" },
                new TownData(){ Town = "چارده سید نصر الدین", Price = "13500", Tag = "" },
                new TownData(){ Town = "چفل بازکیاگوراب", Price = "9600", Tag = "" },
                new TownData(){ Town = "چالک رود تنکابن", Price = "86000", Tag = "شهسوار" },
                new TownData(){ Town = "حاجی بکنده", Price = "21000", Tag = "" },
                new TownData(){ Town = "حسن بکنده دستک", Price = "29000", Tag = "" },
                new TownData(){ Town = "حسن علی ده", Price = "29000", Tag = "" },
                new TownData(){ Town = "حسن کیاده", Price = "16000", Tag = "کیا ده" },
                new TownData(){ Town = "حسن رود", Price = "35000", Tag = "" },
                new TownData(){ Town = "حویق", Price = "105000", Tag = "" },
                new TownData(){ Town = "خشکاروندان", Price = "8000", Tag = "" },
                new TownData(){ Town = "خشک بیجار", Price = "23000", Tag = "" },
                new TownData(){ Town = "خلخال (از اسالم)", Price = "207000", Tag = "" },
                new TownData(){ Town = "خمام", Price = "30000", Tag = "" },
                new TownData(){ Town = "خلخال (از اردبیل)", Price = "255000", Tag = "" },
                new TownData(){ Town = "داخل بالا", Price = "8500", Tag = "" },
                new TownData(){ Town = "داخل پایین", Price = "10000", Tag = "" },
                new TownData(){ Town = "درگاه", Price = "10000", Tag = "" },
                new TownData(){ Town = "دستک", Price = "25000", Tag = "" },
                new TownData(){ Town = "دشمن کرده", Price = "17000", Tag = "" },
                new TownData(){ Town = "دهسر کیاشهر", Price = "10000", Tag = "" },
                new TownData(){ Town = "دهشال", Price = "13000", Tag = "" },
                new TownData(){ Town = "دهکا", Price = "16000", Tag = "" },
                new TownData(){ Town = "دهنه سر سفید رود", Price = "27000", Tag = "" },
                new TownData(){ Town = "دیلمان", Price = "100000", Tag = "" },
                new TownData(){ Town = "دهسر سیاهکل", Price = "14000", Tag = "ده سر" },
                new TownData(){ Town = "دیو شل لنگرود", Price = "18000", Tag = "" },
                new TownData(){ Town = "دیزبن لنگرود", Price = "16000", Tag = "" },
                new TownData(){ Town = "دهبر لشت نشا", Price = "17000", Tag = "" },
                new TownData(){ Town = "دانشگاه مهر استان", Price = "4600", Tag = "مهراستان" },
                new TownData(){ Town = "دادگستری", Price = "4000", Tag = "" },
                new TownData(){ Town = "ذیهنده جاده لشت نشا", Price = "14000", Tag = "" },
                new TownData(){ Town = "رشت یخسازی", Price = "31000", Tag = "یخ سازی" },
                new TownData(){ Town = "بیمارستان قائم", Price = "35000", Tag = "قایم" },
                new TownData(){ Town = "رشت رسول اکرم", Price = "35000", Tag = "" },
                new TownData(){ Town = "پیر بازار", Price = "35000", Tag = "" },
                new TownData(){ Town = "رامسر", Price = "60000", Tag = "" },
                new TownData(){ Town = "رحیم اباد", Price = "42000", Tag = "آباد" },
                new TownData(){ Town = "رستم اباد", Price = "55000", Tag = "آباد" },
                new TownData(){ Town = "رشت جانبازان", Price = "25000", Tag = "" },
                new TownData(){ Town = "رشت شهر داری", Price = "27000", Tag = "شهرداری" },
                new TownData(){ Town = "رشت فرودگاه - گلسار", Price = "27000", Tag = "" },
                new TownData(){ Town = "رشت اباد", Price = "11500", Tag = "آباد رشتاباد" },
                new TownData(){ Town = "رضوان شهر", Price = "69000", Tag = "" },
                new TownData(){ Town = "رودبار", Price = "55000", Tag = "" },
                new TownData(){ Town = "رودبارکی", Price = "14000", Tag = "" },
                new TownData(){ Town = "رودبنه", Price = "8000", Tag = "" },
                new TownData(){ Town = "رودسر", Price = "30000", Tag = "" },
                new TownData(){ Town = "ریشونده دهشال", Price = "17000", Tag = "" },
                new TownData(){ Town = "رشت پورسینا", Price = "29000", Tag = "پور سینا" },
                new TownData(){ Town = "رشت گلسار", Price = "29000", Tag = "" },
                new TownData(){ Town = "زارم کلایه", Price = "10500", Tag = "زارمکلایه" },
                new TownData(){ Town = "زنجان", Price = "200000", Tag = "" },
                new TownData(){ Town = "زیاور شفت", Price = "60000", Tag = "" },
                new TownData(){ Town = "زیبا کنار از لشت نشا", Price = "23000", Tag = "زیباکنار" },
                new TownData(){ Town = "زهنده از جاده لشت نشا", Price = "14000", Tag = "" },
                new TownData(){ Town = "سادات محله رامسر", Price = "75000", Tag = "" },
                new TownData(){ Town = "ساری", Price = "220000", Tag = "" },
                new TownData(){ Town = "سالستان امشل و دانشگاه", Price = "4500", Tag = "" },
                new TownData(){ Town = "سالکده", Price = "14000", Tag = "" },
                new TownData(){ Town = "سد سنگر", Price = "21000", Tag = "" },
                new TownData(){ Town = "سد قوام", Price = "12500", Tag = "" },
                new TownData(){ Town = "سرشکه", Price = "15000", Tag = "" },
                new TownData(){ Town = "سلمان شهر", Price = "180000", Tag = "" },
                new TownData(){ Town = "سلیمان داراب رشت", Price = "22000", Tag = "" },
                new TownData(){ Town = "سلیم چاف", Price = "22000", Tag = "سلیمچاف" },
                new TownData(){ Town = "سنگر", Price = "27500", Tag = "" },
                new TownData(){ Town = "سوخته کوه", Price = "10000", Tag = "" },
                new TownData(){ Town = "سه راه شفت", Price = "45000", Tag = "" },
                new TownData(){ Town = "سیاهکل", Price = "27000", Tag = "" },
                new TownData(){ Town = "سیاه کوچه", Price = "7000", Tag = "سیاهکوچه" },
                new TownData(){ Town = "سلکول بازکیاگوراب", Price = "10000", Tag = "سل کول" },
                new TownData(){ Town = "سراوان", Price = "45000", Tag = "" },
                new TownData(){ Town = "سالستان دانشگاه", Price = "45000", Tag = "" },
                new TownData(){ Town = "سیاهکل زندان ایزبرم", Price = "21000", Tag = "" },
                new TownData(){ Town = "سیاهکل ایستگاه دمچال", Price = "20000", Tag = "" },
                new TownData(){ Town = "شهر صنعتی سیاهکل", Price = "21000", Tag = "" },
                new TownData(){ Town = "شاقاچی", Price = "32000", Tag = "" },
                new TownData(){ Town = "شاندرمن", Price = "69000", Tag = "" },
                new TownData(){ Town = "شرف شاده", Price = "23000", Tag = "شرفشاده" },
                new TownData(){ Town = "ششکل بالا", Price = "14500", Tag = "شیشکل" },
                new TownData(){ Town = "ششکل پایین", Price = "15000", Tag = "شیشکل" },
                new TownData(){ Town = "شفت", Price = "55000", Tag = "" },
                new TownData(){ Town = "شلمان", Price = "25000", Tag = "" },
                new TownData(){ Town = "شیخ علی کلایه", Price = "20000", Tag = "" },
                new TownData(){ Town = "شیر جو پشت", Price = "15000", Tag = "شیرجو" },
                new TownData(){ Town = "شکاکم بازکیاگوراب", Price = "13000", Tag = "بازکیا گوراب" },
                new TownData(){ Town = "صداپشته", Price = "9000", Tag = "صدا پشته" },
                new TownData(){ Town = "صفرابسته صنوبر بالا", Price = "7000", Tag = "صفرا بسته" },
                new TownData(){ Town = "صفرابسته پوشل", Price = "10500", Tag = "" },
                new TownData(){ Town = "صیقل سرایه دهکا", Price = "20000", Tag = "" },
                new TownData(){ Town = "صومعه سرا", Price = "50000", Tag = "" },
                new TownData(){ Town = "صیقل ده درگاه", Price = "12500", Tag = "صیقلده" },
                new TownData(){ Town = "صیقل سرایه درگاه", Price = "10500", Tag = "صیقلسرایه" },
                new TownData(){ Town = "صفرابسته صنوبر پایین", Price = "6000", Tag = "صفرا بسته" },
                new TownData(){ Town = "طالب اباد انزلی", Price = "38000", Tag = "آباد" },
                new TownData(){ Town = "طارمسر", Price = "17000", Tag = "طارم سر" },
                new TownData(){ Town = "طالب اباد", Price = "21000", Tag = "آباد" },
                new TownData(){ Town = "طاهرگوراب", Price = "48000", Tag = "طاهر گوراب" },
                new TownData(){ Town = "عبدالله اباد", Price = "15000", Tag = "آباد" },
                new TownData(){ Town = "عسکر اباد کیاشهر", Price = "21000", Tag = "عسکراباد آباد" },
                new TownData(){ Town = "عباس اباد", Price = "9000", Tag = "آباد" },
                new TownData(){ Town = "غازیان", Price = "46000", Tag = "انزلی" },
                new TownData(){ Town = "فخراباد لشت نشا", Price = "21000", Tag = "آباد فخر اباد" },
                new TownData(){ Town = "فشتم بالا", Price = "10500", Tag = "فوشتم فوشتوم" },
                new TownData(){ Town = "فشتم پایین", Price = "11500", Tag = "فوشتم فوشتوم" },
                new TownData(){ Town = "فوشازده", Price = "14000", Tag = "" },
                new TownData(){ Town = "فومن", Price = "60000", Tag = "" },
                new TownData(){ Town = "فتیده شلمان", Price = "31000", Tag = "" },
                new TownData(){ Town = "فومن اقا سید جواد", Price = "48000", Tag = "آقا" },
                new TownData(){ Town = "فریدون کنار", Price = "178500", Tag = "" },
                new TownData(){ Town = "قائم شهر", Price = "210000", Tag = "" },
                new TownData(){ Town = "قزوین", Price = "125000", Tag = "" },
                new TownData(){ Town = "قم", Price = "310000", Tag = "" },
                new TownData(){ Town = "قلعه رود خان", Price = "83000", Tag = "" },
                new TownData(){ Town = "کارسیدان", Price = "8000", Tag = "" },
                new TownData(){ Town = "کتشست ابادان از چهارده", Price = "14000", Tag = "" },
                new TownData(){ Town = "کچلام", Price = "22000", Tag = "" },
                new TownData(){ Town = "کرج", Price = "190000", Tag = "" },
                new TownData(){ Town = "کاشان", Price = "483000", Tag = "" },
                new TownData(){ Town = "کسما", Price = "46000", Tag = "" },
                new TownData(){ Town = "کشل", Price = "6000", Tag = "" },
                new TownData(){ Town = "کلاچای", Price = "41000", Tag = "" },
                new TownData(){ Town = "کولده بالا", Price = "8000", Tag = "" },
                new TownData(){ Town = "کولده پایین", Price = "10000", Tag = "" },
                new TownData(){ Town = "کومله", Price = "25000", Tag = "" },
                new TownData(){ Town = "کومچال بالا", Price = "5000", Tag = "" },
                new TownData(){ Town = "کومچال پایین", Price = "7000", Tag = "" },
                new TownData(){ Town = "کنارسر کوچصفهان", Price = "21000", Tag = "کنار سر" },
                new TownData(){ Town = "کنف گوراب", Price = "7000", Tag = "" },
                new TownData(){ Town = "کوچصفهان", Price = "17000", Tag = "" },
                new TownData(){ Town = "کورکا داخل محله", Price = "4500", Tag = "" },
                new TownData(){ Town = "کهنه رود پشت", Price = "23000", Tag = "" },
                new TownData(){ Town = "کیاشهر بالا", Price = "14000", Tag = "" },
                new TownData(){ Town = "کیسم بالا", Price = "8000", Tag = "" },
                new TownData(){ Town = "کیسم پایین", Price = "10000", Tag = "" },
                new TownData(){ Town = "کینچاه", Price = "8000", Tag = "" },
                new TownData(){ Town = "کیاسر سد قوام", Price = "15000", Tag = "" },
                new TownData(){ Town = "کوکه سد قوام", Price = "13000", Tag = "" },
                new TownData(){ Town = "کورنده", Price = "21000", Tag = "" },
                new TownData(){ Town = "کماچال (از نیاکو)", Price = "6000", Tag = "" },
                new TownData(){ Town = "کیاشهر کوی امام", Price = "15000", Tag = "" },
                new TownData(){ Town = "کماچال میان محله", Price = "7000", Tag = "" },
                new TownData(){ Town = "کماچال رجه سر", Price = "6000", Tag = "" },
                new TownData(){ Town = "کیاشهر رجایی", Price = "16000", Tag = "" },
                new TownData(){ Town = "گیلوا", Price = "21000", Tag = "" },
                new TownData(){ Town = "گشتاجان", Price = "14000", Tag = "" },
                new TownData(){ Town = "گاویه (امامده)", Price = "14000", Tag = "" },
                new TownData(){ Town = "گرباسده (اول اسفالت)", Price = "13000", Tag = "" },
                new TownData(){ Town = "گرباسده داخل", Price = "13000 - 14000", Tag = "گرباس ده گرباز" },
                new TownData(){ Town = "گسگر محله رودسر", Price = "35000", Tag = "" },
                new TownData(){ Town = "گفشه لشت نشا", Price = "20000", Tag = "" },
                new TownData(){ Town = "گورابزرمیخ", Price = "48000", Tag = "گوراب زر میخ" },
                new TownData(){ Town = "گورابسر", Price = "45000", Tag = "گوراب سر" },
                new TownData(){ Town = "گوهردان", Price = "7000", Tag = "" },
                new TownData(){ Town = "گیلده بالا", Price = "16000", Tag = "" },
                new TownData(){ Town = "گیلده پایین", Price = "17000", Tag = "" },
                new TownData(){ Town = "گل سرخ رامسر", Price = "50000", Tag = "" },
                new TownData(){ Town = "گرگان", Price = "417000", Tag = "" },
                new TownData(){ Town = "گل رودبار بالا", Price = "16000", Tag = "" },
                new TownData(){ Town = "گل رودبار پایین", Price = "17000", Tag = "" },
                new TownData(){ Town = "گوراب جوار", Price = "7000", Tag = "" },
                new TownData(){ Town = "لیسار", Price = "96000", Tag = "" },
                new TownData(){ Town = "لبک محله (کوچه شهید شاداب)", Price = "15000", Tag = "" },
                new TownData(){ Town = "لیلا کوه لنگرود", Price = "24000", Tag = "" },
                new TownData(){ Town = "لاشه", Price = "13000", Tag = "" },
                new TownData(){ Town = "لاشیدان", Price = "13000", Tag = "" },
                new TownData(){ Town = "لاکوژده", Price = "12000", Tag = "" },
                new TownData(){ Town = "لاهیجان زیر کوه دانشگاه", Price = "12000", Tag = "" },
                new TownData(){ Town = "لاهیجان", Price = "11000", Tag = "" },
                new TownData(){ Town = "لاهیجان بام سبز", Price = "13000", Tag = "" },
                new TownData(){ Town = "لبشگاه", Price = "10000", Tag = "" },
                new TownData(){ Town = "لسکوه ولشام", Price = "18500", Tag = "" },
                new TownData(){ Town = "لسکوکلایه از سوخته کوه", Price = "14000", Tag = "" },
                new TownData(){ Town = "لسکوکلایه از کیاشهر", Price = "18000", Tag = "" },
                new TownData(){ Town = "لشت نشا", Price = "15000", Tag = "" },
                new TownData(){ Town = "لفنجان از جاده سیاهکل", Price = "16000", Tag = "" },
                new TownData(){ Town = "لله وچه سر از راه انبارسر", Price = "22000", Tag = "" },
                new TownData(){ Town = "لفوط بالا", Price = "6000", Tag = "" },
                new TownData(){ Town = "لفوط پایین", Price = "8500", Tag = "" },
                new TownData(){ Town = "لنگرود", Price = "18000", Tag = "" },
                new TownData(){ Town = "لوخ جنب پمپ بنزین", Price = "23000", Tag = "" },
                new TownData(){ Town = "لوخ به طرف گیلده", Price = "21000", Tag = "" },
                new TownData(){ Town = "لولمان", Price = "12500", Tag = "" },
                new TownData(){ Town = "لونک دیلمان", Price = "48000", Tag = "" },
                new TownData(){ Town = "لب دریا از راه انبارسر", Price = "22000", Tag = "" },
                new TownData(){ Town = "لیالستان", Price = "14000", Tag = "" },
                new TownData(){ Town = "لیچاه", Price = "16000", Tag = "" },
                new TownData(){ Town = "لنگر ابرود", Price = "96000", Tag = "آبرود آب رود" },
                new TownData(){ Town = "لوشان", Price = "76000", Tag = "" },
                new TownData(){ Town = "لاکانشهر - زندان لاکان", Price = "41600", Tag = "لاکان شهر" },
                new TownData(){ Town = "لسکو (جاده لشت نشا)", Price = "15000", Tag = "" },
                new TownData(){ Town = "مرغداری سپید کنار", Price = "7000", Tag = "مرغ داری" },
                new TownData(){ Town = "مالفجان سیاهکل", Price = "15000", Tag = "" },
                new TownData(){ Town = "مالفجان تا کارخانه", Price = "14000", Tag = "" },
                new TownData(){ Town = "مزرن اباد چالوس", Price = "16700", Tag = "آباد" },
                new TownData(){ Town = "محمود اباد امل", Price = "160000", Tag = "آباد آمل" },
                new TownData(){ Town = "میانه", Price = "46000", Tag = "" },
                new TownData(){ Town = "ماسال", Price = "70000", Tag = "" },
                new TownData(){ Town = "ماسوله", Price = "80000", Tag = "" },
                new TownData(){ Town = "ماشک تهرانچی", Price = "15000", Tag = "" },
                new TownData(){ Town = "ماشک سپهداری", Price = "11000", Tag = "" },
                new TownData(){ Town = "محسن اباد دستک", Price = "25000", Tag = "" },
                new TownData(){ Town = "مردمکده", Price = "6500", Tag = "" },
                new TownData(){ Town = "منجیل", Price = "75000", Tag = "" },
                new TownData(){ Town = "محسن اباد کیاشهر", Price = "13000", Tag = "" },
                new TownData(){ Town = "مبارک اباد فشتم", Price = "14000", Tag = "فوشتوم فوشتم" },
                new TownData(){ Town = "متل قو", Price = "96000", Tag = "" },
                new TownData(){ Town = "منطقه ازاد انزلی", Price = "36000", Tag = "آزاد" },
                new TownData(){ Town = "مشهد مقدس", Price = "700000", Tag = "" },
                new TownData(){ Town = "ناصر کیاده از رودبنه", Price = "25000", Tag = "" },
                new TownData(){ Town = "نیاکو اول", Price = "6500", Tag = "" },
                new TownData(){ Town = "نیاکو اخر", Price = "7000", Tag = "" },
                new TownData(){ Town = "نقده", Price = "520000", Tag = "" },
                new TownData(){ Town = "نوبیجار لاهیجان", Price = "14000", Tag = "" },
                new TownData(){ Town = "نازکسرا", Price = "7000", Tag = "نازک سرا" },
                new TownData(){ Town = "نبی دهکا", Price = "10000", Tag = "" },
                new TownData(){ Town = "نشتارود", Price = "83000", Tag = "" },
                new TownData(){ Town = "نصراله اباد", Price = "18000", Tag = "نصر الله نصرالله آباد" },
                new TownData(){ Town = "نقره ده", Price = "11000", Tag = "" },
                new TownData(){ Town = "نور مازندران", Price = "167000", Tag = "" },
                new TownData(){ Town = "نوشر رودبنه", Price = "21000", Tag = "" },
                new TownData(){ Town = "نوشر سوخته کوه", Price = "10000", Tag = "" },
                new TownData(){ Town = "نوده لشت نشا", Price = "18000", Tag = "" },
                new TownData(){ Town = "نمک ابرود", Price = "115000", Tag = "آبرود آب اب رود" },
                new TownData(){ Town = "نوبیجار محله کیاشهر", Price = "12000", Tag = "نو بیجار" },
                new TownData(){ Town = "نخجیر کلاسه لاهیجان", Price = "14000", Tag = "" },
                new TownData(){ Town = "نوشهر", Price = "126000", Tag = "" },
                new TownData(){ Town = "واجارگاه", Price = "55000", Tag = "" },
                new TownData(){ Town = "هتل فجر لاهیجان", Price = "15000", Tag = "" },
                new TownData(){ Town = "هچیرود", Price = "108000", Tag = "" },
                new TownData(){ Town = "هشتپر تالش", Price = "96000", Tag = "" },
                new TownData(){ Town = "همدان", Price = "345000", Tag = "" },
                new TownData(){ Town = "هندخاله", Price = "60000", Tag = "" },
                new TownData(){ Town = "هشتگرد", Price = "190000", Tag = "" },
                new TownData(){ Town = "هیدج", Price = "184000", Tag = "" },
                new TownData(){ Town = "هشتپر تالش", Price = "96000", Tag = "هشت پر هشپر" },
                new TownData(){ Town = "آستانه - فرغون سازی", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - انبار شرکت کود شیمیایی", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - مدیریت کشاورزی", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - مدرسه استثنایی کورکا", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - مدرسه حشمت کورکا", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - کشتارگاه مرغ کیسم", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - تالار عروسی بانی چاو", Price = "7000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - هنرستان دکتر دشتستانی", Price = "6000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - تالار گلها", Price = "6000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - دانشگاه پیام نور", Price = "4000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - داخل شهر", Price = "3500", Tag = "استانه" },
                new TownData(){ Town = "آستانه - تغییر مسیر", Price = "800", Tag = "استانه" },
                new TownData(){ Town = "آستانه - گردش کامل ساعتی", Price = "12000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - توقف ساعتی", Price = "7000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - پایه کرایه برگشتی", Price = "(50 درصد)", Tag = "استانه" },
                new TownData(){ Town = "آستانه- روکش گیل", Price = "3500", Tag = "استانه" },
                new TownData(){ Town = "آستانه - کیلومتری اسفالت", Price = "800", Tag = "استانه آسفالت" },
                new TownData(){ Town = "آستانه - کیلومتری خاکی", Price = "1200", Tag = "استانه" },
                new TownData(){ Town = "آستانه - ابیاری اول", Price = "3500", Tag = "استانه" },
                new TownData(){ Town = "آستانه - سید بر ناصر کیاده", Price = "24000", Tag = "استانه" },
                new TownData(){ Town = "آستانه - داخل شهر شب ها", Price = "3500", Tag = "استانه شبها" },
                new TownData(){ Town = "حویق", Price = "90000", Tag = "" },
                new TownData(){ Town = "کیاشهر پیست موتور سواری", Price = "15000", Tag = "" },
                new TownData(){ Town = "کیاشهر پل شنا خواهران", Price = "16000", Tag = "" },
                new TownData(){ Town = "کیاشهر لنج سازی", Price = "14000", Tag = "" },
                new TownData(){ Town = "کیاشهر ابتدای سنگ چین", Price = "15000", Tag = "" },
                new TownData(){ Town = "کیاشهر دماغه سنگ چین", Price = "15000", Tag = "استانه" },
                new TownData(){ Town = "کیاشهر پل امام زاده", Price = "14000", Tag = "امامزاده" },
                new TownData(){ Town = "کیاهشر حراست دریا", Price = "15000", Tag = "" },
                new TownData(){ Town = "کیاشهر تالار قصر شیرین", Price = "14000", Tag = "" },
                new TownData(){ Town = "کیاشهر تالار عروس گیلان", Price = "15000", Tag = "" },
                new TownData(){ Town = "کیاشهر داخل صدا و سیما", Price = "14000", Tag = "" },
                new TownData(){ Town = "کیاشهر نوبیجار محله", Price = "9500", Tag = "" },
                new TownData(){ Town = "دانشگاه مهر استان", Price = "4000", Tag = "مهراستان مهرآستان آستان" },
                new TownData(){ Town = "تالار اطلس", Price = "5000", Tag = "" },
                new TownData(){ Town = "تالار ونوس", Price = "5000", Tag = "" },
                new TownData(){ Town = "تالار مرسده", Price = "5000", Tag = "" },
                new TownData(){ Town = "تالار دهدار", Price = "5000", Tag = "" },
                new TownData(){ Town = "دادگستری", Price = "3500", Tag = "" },
                new TownData(){ Town = "تالار احمد", Price = "6000", Tag = "" },

            };

            context.TownData.AddRange(data);

            context.SaveChanges();
        }

        private static void AddDefaultDriver(KhorshidContext context)
        {
            context.Drivers.Add(new Driver
            {
                Name = "فروزان بی غم",
                Description = "مدیر آژانس"
            });

            context.SaveChanges();
        }

    }
}
